# Generated by Django 2.2.4 on 2019-12-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task_duration', models.DateTimeField(blank=True, null=True)),
                ('todo_type', models.CharField(blank=True, choices=[('p', 'personal'), ('f', 'family'), ('h', 'house'), ('m', 'misc'), ('s', 'school')], default='m', max_length=1)),
            ],
            options={
                'ordering': ['title', 'create_at'],
            },
        ),
    ]
