# Generated by Django 3.0.2 on 2020-01-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inboxApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversationDB',
        ),
    ]
