# Generated by Django 3.0.2 on 2020-01-11 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inboxApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxdb',
            name='users_inbox',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_inbox', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inboxdb',
            name='messages',
            field=models.CharField(blank=True, default='Users default message', max_length=50, null=True),
        ),
    ]
