# Generated by Django 3.0.2 on 2020-01-11 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inboxApp', '0003_auto_20200111_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboxdb',
            name='users_inbox',
        ),
        migrations.AddField(
            model_name='inboxdb',
            name='body',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='inboxdb',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inboxdb',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DirectMsgDB',
        ),
    ]
