# Generated by Django 3.0.2 on 2020-01-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inboxApp', '0004_auto_20200123_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='conversation_name',
            field=models.CharField(default="User1 and User2's Conversation", max_length=200, null=True),
        ),
    ]
