# Generated by Django 3.0.2 on 2020-01-14 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inboxApp', '0005_auto_20200113_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconversation',
            name='posts',
        ),
    ]
