# Generated by Django 3.0.2 on 2020-01-14 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inboxApp', '0006_remove_userconversation_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inboxdb',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userconversation',
            options={'verbose_name_plural': 'Inboxes'},
        ),
        migrations.RenameField(
            model_name='inboxdb',
            old_name='published',
            new_name='sent_date',
        ),
        migrations.RenameField(
            model_name='userconversation',
            old_name='sent_date',
            new_name='published',
        ),
        migrations.RemoveField(
            model_name='inboxdb',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='inboxdb',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='userconversation',
            name='conversation',
        ),
        migrations.AddField(
            model_name='inboxdb',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='inboxApp.UserConversation'),
        ),
        migrations.AddField(
            model_name='userconversation',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userconversation',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
