# Generated by Django 3.0.2 on 2020-01-28 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inboxApp', '0007_auto_20200127_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessages',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
