# Generated by Django 3.0.2 on 2020-01-28 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inboxApp', '0008_auto_20200127_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessages',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
