# Generated by Django 3.0.2 on 2020-01-16 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inboxApp', '0008_auto_20200113_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inboxdb',
            options={'verbose_name_plural': 'User Messages'},
        ),
    ]
