# Generated by Django 3.0.2 on 2020-01-08 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('social_media', models.URLField(blank=True, default='', null=True)),
                ('follower_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('experience', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('portfolio_links', models.URLField(blank=True, default='', null=True)),
                ('bio', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('friends', models.IntegerField(blank=True, default=0, null=True)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('photo_library', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
