# Generated by Django 3.0.2 on 2020-01-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200114_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='City here', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='Country here', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='follower_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_media',
            field=models.URLField(default='Add link https://www.instagram.com/yourprofile'),
        ),
    ]
