# Generated by Django 3.0.2 on 2020-01-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200117_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='jumbo_bg',
            field=models.ImageField(default='default_bg', upload_to='profile/profile_backgrounds/'),
        ),
    ]
