# Generated by Django 3.0.2 on 2020-01-18 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200117_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='jumbo_bg',
            new_name='cover_picture',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
