# Generated by Django 3.0.2 on 2020-01-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200117_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_picture',
            field=models.ImageField(default='default_bg.webp', upload_to='profile/profile_backgrounds/'),
        ),
    ]
