# Generated by Django 3.0.2 on 2020-01-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200117_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_picture',
            field=models.ImageField(default='default_bg.jpg', upload_to='profile/profile_backgrounds/'),
        ),
    ]
