# Generated by Django 3.0.2 on 2020-01-18 04:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200117_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhotoLibrary',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/profile_library')),
            ],
        ),
    ]
