# Generated by Django 3.0.2 on 2020-01-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profilephotolibrary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilephotolibrary',
            old_name='photo',
            new_name='photo_post',
        ),
    ]
