# Generated by Django 3.0.2 on 2020-01-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200117_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUserPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='profilephotolibrary',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
