# Generated by Django 3.0.2 on 2020-01-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200120_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_picture',
            field=models.ImageField(blank=True, default='static_images/default_bg.jpg', null=True, upload_to='profile/profile_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static_images/default_profile.jpg', null=True, upload_to='profile/profile_images/'),
        ),
    ]
