# Generated by Django 3.0.2 on 2020-01-22 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200120_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePhotoLibrary',
        ),
        migrations.AddField(
            model_name='profileuserphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='User_photo_library'),
        ),
        migrations.AddField(
            model_name='profileuserphoto',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.ProfileUserPost'),
        ),
        migrations.AddField(
            model_name='profileuserpost',
            name='title',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='profileuserpost',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
