# Generated by Django 3.0.2 on 2020-01-30 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200121_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cliques',
            new_name='friends',
        ),
    ]
