# Generated by Django 3.0.2 on 2020-01-30 23:29

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_photolibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photolibrary',
            name='file',
            field=sorl.thumbnail.fields.ImageField(upload_to=''),
        ),
    ]
