# Generated by Django 3.0.2 on 2020-01-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200130_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photolibrary',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
