# Generated by Django 3.0.2 on 2020-02-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20200130_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilelibrary',
            options={'verbose_name_plural': 'Library Photos'},
        ),
        migrations.AlterModelOptions(
            name='profilephotos',
            options={'verbose_name_plural': 'UserProfile Photos'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experience',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_picture',
            field=models.ImageField(blank=True, default='static_images/default_bg.jpg', null=True, upload_to='profile/profile_backgrounds/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='../../static_images/default_profile.jpg', null=True, upload_to='profile/profile_images/'),
        ),
    ]
