# Generated by Django 3.0.2 on 2020-02-02 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20200202_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends_list',
            field=models.ManyToManyField(related_name='friends_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
