# Generated by Django 3.0.2 on 2020-02-04 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20200203_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
    ]
