# Generated by Django 3.0.3 on 2020-02-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, choices=[('PHOTOGRAPHER', 'Photographer'), ('CREATOR', 'Creator')], max_length=12, null=True),
        ),
    ]
