# Generated by Django 3.0.3 on 2020-02-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_userprofile_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, choices=[('Photographer', 'Photographer'), ('Creator', 'Creator')], max_length=12, null=True),
        ),
    ]
