# Generated by Django 3.0.3 on 2020-02-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20200211_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, choices=[('Photographer', 'Photographer'), ('Influencer', 'Influencer')], max_length=12, null=True),
        ),
    ]
