# Generated by Django 2.2.4 on 2019-12-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
