# Generated by Django 2.2.4 on 2019-12-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NameGen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlibrary',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
