# Generated by Django 2.2.4 on 2019-12-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urls',
            options={'ordering': ['code', 'url']},
        ),
    ]
